name: YellowstoneWaterfallproject
favicon: null
layout_spectrum: 0.07289195456542075
typography_spectrum: 0.2576274105813354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8029222406912595
  lightness: 0.6730432079639286
  saturation: 0.035963128320872784
  rhythmicContrast: 0.35838960809633136
purpose: []
